version: '3.1'
services:
  cloud-config:
    container_name: cloud-config
    image: cloud-config
    depends_on:
      - postgres
    build:
      context: ../docker
      dockerfile: cloud-config.Dockerfile
    ports:
      - "8888:8888"
  eureka-server:
    container_name: eureka-server
    image: eureka-server
#    depends_on:
#      - cloud-config
    build:
      context: ../docker
      dockerfile: eureka-server.Dockerfile
    ports:
      - "8761:8761"
  postgres:
    image: postgres:13  # Use the desired version
    environment:
      POSTGRES_DB: cloud-config1  # Name of the database to be created on image startup
      POSTGRES_USER: postgres      # PostgreSQL user
      POSTGRES_PASSWORD: 123456  # PostgreSQL password
    ports:
      - "5433:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

# phiên bản này cho eureka chạy khoong phu thuoc vao config-server, chayj ngon, mai thu chạy phien ban ket noi voi config-server di